Trait {
	#name : 'ScpInstrumentationHandler',
	#category : 'Scopeo-Instrumentation-GenericMethodModification',
	#package : 'Scopeo-Instrumentation',
	#tag : 'GenericMethodModification'
}

{ #category : 'hooks' }
ScpInstrumentationHandler >> onAssignmentEvent: aAssignmentEvent [
]

{ #category : 'hooks' }
ScpInstrumentationHandler >> onMessageEvent: aMessageEvent [

	
]

{ #category : 'hooks' }
ScpInstrumentationHandler >> onMethodEvent: aMethodEvent [
]
