Class {
	#name : #ScpInstrumentationHandler,
	#superclass : #Object,
	#category : #'Scopeo-Instrumentation'
}

{ #category : #'events handling' }
ScpInstrumentationHandler >> method: aSelector sender: aSender receiver: aReceiver arguments: anArguments [
]

{ #category : #'as yet unclassified' }
ScpInstrumentationHandler >> node: aNodeId assignment: aVariable object: anObject value: aValue [
]

{ #category : #'as yet unclassified' }
ScpInstrumentationHandler >> node: aNodeId message: aSelector sender: aSender receiver: aReceiver arguments: anArguments [
]

{ #category : #'as yet unclassified' }
ScpInstrumentationHandler >> node: aNodeId return: aValue [
]

{ #category : #'as yet unclassified' }
ScpInstrumentationHandler >> node: aNodeId super: aSelector sender: aSender arguments: anArguments [
]
