Class {
	#name : #ScpInstrumentationHandler,
	#superclass : #Object,
	#category : #'Scopeo-Instrumentation'
}

{ #category : #'events handling' }
ScpInstrumentationHandler >> onAssignment: aVariable of: anObject value: aValue [
]

{ #category : #'events handling' }
ScpInstrumentationHandler >> onMethodCall: aMethodSelector from: aSender to: aReceiver with: aArguments [
]

{ #category : #'as yet unclassified' }
ScpInstrumentationHandler >> onMethodReturn: aValue [
]

{ #category : #'as yet unclassified' }
ScpInstrumentationHandler >> onSuperCall: aSelector from: aSender with: anArguments [
]
