Class {
	#name : 'ScpTraceSourceMenuDialogValidateEvent',
	#superclass : 'Announcement',
	#instVars : [
		'value'
	],
	#category : 'Scopeo-Method-Instrumentation-Installer-Source-Menu-UI',
	#package : 'Scopeo-Method-Instrumentation-Installer',
	#tag : 'Source-Menu-UI'
}

{ #category : 'accessing' }
ScpTraceSourceMenuDialogValidateEvent >> value [

	^ value
]

{ #category : 'accessing' }
ScpTraceSourceMenuDialogValidateEvent >> value: anObject [

	value := anObject
]
